var First_Name = "Manya";
console.log(First_Name);
var Last_Name = "Shah";
console.log(Last_Name)
var Full_Name = First_Name.concat(Last_Name);
console.log(Full_Name);
var Name_Count = Full_Name.length;
console.log(Name_Count);
var Replace_Name = "Hemang";
console.log(Replace_Name);
var Replacement = Replace_Name.replace("Hemang","Manya");
console.log(Replacement);
var Low_Case = "HELLO WORLD!";
console.log(Low_Case);
var Convert = Low_Case.toLowerCase();
console.log(Convert);
var Upper_Case = "i am manya shah.";
console.log(Upper_Case);
var Convert_2 = Upper_Case.toUpperCase();
console.log(Convert_2);
var Square_Root = Math.sqrt(16);
console.log(Square_Root);
var Max_Number = Math.max(1, 3, 5, 7, 9);
console.log(Max_Number);
var Min_Number = Math.min(2, 4, 6, 8, 10);
console.log(Min_Number);
var Power = Math.pow (9, 6);
console.log(Power);
var x = 4;
var y = 8;
var Add = x + y;
console.log(Add);
var a = 15;
var b = 13;
var Subtract = a - b;
console.log(Subtract);